// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dduzuxhxvinboilpfgvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkdXp1eGh4dmluYm9pbHBmZ3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDQ0ODksImV4cCI6MjA2NTQyMDQ4OX0.Y5Gha8DYtbk_4Eas6EF0uL_tvVKRqoAgqFdQ0bHvMCU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);